import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from '@tanstack/react-router'
import { Button } from '@/components/ui/button'
import { SettingsPageContent, SettingsRow, SettingsSection } from '@/components/settings/SettingsPrimitives'
import { useAppContext } from '@/lib/app-context'
import { type Account, settingsInputClass, useSettingsRequest } from './settingsApi'

export default function UserSettingsPage() {
    const { accountId } = useParams({ strict: false }) as { accountId: string }
    const creating = accountId === 'new'; const { user } = useAppContext(); const request = useSettingsRequest(); const navigate = useNavigate()
    const [account, setAccount] = useState<Account | null>(null); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<'admin' | 'user'>('user'); const [memory, setMemory] = useState(''); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false)
    const load = useCallback(async () => { if (creating || user.role !== 'admin') return; try { const accounts = (await request<{ accounts: Account[] }>('/api/accounts')).accounts; const found = accounts.find(item => item.id === Number(accountId)) ?? null; setAccount(found); setMemory(found?.memory ?? '') } catch (cause) { setError(cause instanceof Error ? cause.message : '加载失败') } }, [accountId, creating, request, user.role])
    useEffect(() => { void load() }, [load])
    const mutate = async (body: object) => { if (!account) return; setPending(true); try { await request(`/api/accounts/${account.id}`, { method: 'PATCH', body: JSON.stringify(body) }); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : '操作失败') } finally { setPending(false) } }
    if (user.role !== 'admin') return <SettingsPageContent title="用户管理"><SettingsSection><SettingsRow label="仅管理员可访问" /></SettingsSection></SettingsPageContent>
    if (creating) return <SettingsPageContent title="新建用户"><SettingsSection><form className="space-y-3 p-3" onSubmit={event => { event.preventDefault(); setPending(true); void request<{ account: Account }>('/api/accounts', { method: 'POST', body: JSON.stringify({ username, password, role }) }).then(result => navigate({ to: '/settings/fork/users/$accountId', params: { accountId: String(result.account.id) } })).catch(cause => setError(cause instanceof Error ? cause.message : '创建失败')).finally(() => setPending(false)) }}><input className={settingsInputClass} placeholder="用户名" value={username} onChange={event => setUsername(event.target.value)} /><input className={settingsInputClass} type="password" placeholder="初始密码（至少 8 位）" value={password} onChange={event => setPassword(event.target.value)} /><select className={settingsInputClass} value={role} onChange={event => setRole(event.target.value as 'admin' | 'user')}><option value="user">普通用户</option><option value="admin">管理员</option></select>{error ? <div role="alert" className="text-sm text-red-500">{error}</div> : null}<div className="flex justify-end"><Button disabled={!username.trim() || password.length < 8 || pending}>创建</Button></div></form></SettingsSection></SettingsPageContent>
    if (!account) return <SettingsPageContent title="用户管理"><SettingsSection><SettingsRow label={error ?? '正在加载…'} /></SettingsSection></SettingsPageContent>
    const current = account.id === user.id
    return <SettingsPageContent title={account.username} description={account.defaultNamespace}><SettingsSection title="账号"><SettingsRow label="系统角色" trailing={<Button size="sm" variant="outline" disabled={current || pending} onClick={() => void mutate({ role: account.role === 'admin' ? 'user' : 'admin' })}>{account.role}</Button>} /><SettingsRow label="账号状态" trailing={<Button size="sm" variant="outline" disabled={current || pending} onClick={() => void mutate({ disabled: account.disabledAt === null })}>{account.disabledAt ? '启用' : '禁用'}</Button>} /><SettingsRow label="重置密码"><div className="mt-2 flex gap-2"><input className={settingsInputClass} type="password" placeholder="新密码（至少 8 位）" value={password} onChange={event => setPassword(event.target.value)} /><Button disabled={password.length < 8 || pending} onClick={() => void mutate({ password }).then(() => setPassword(''))}>保存</Button></div></SettingsRow></SettingsSection><SettingsSection title="用户记忆"><div className="space-y-3 p-3"><textarea className={`${settingsInputClass} min-h-28 resize-y`} value={memory} maxLength={4000} onChange={event => setMemory(event.target.value)} /><div className="flex justify-end"><Button disabled={pending} onClick={() => void mutate({ memory: memory.trim() || null })}>保存</Button></div></div></SettingsSection>{!current ? <SettingsSection title="危险操作"><SettingsRow label="删除账号" trailing={<Button variant="destructive" disabled={pending} onClick={() => { if (window.confirm(`确定删除 ${account.username}？`)) { setPending(true); void request(`/api/accounts/${account.id}`, { method: 'DELETE' }).then(() => navigate({ to: '/settings/fork/users' })).finally(() => setPending(false)) } }}>删除</Button>} /></SettingsSection> : null}</SettingsPageContent>
}
