export const RPC_METHODS = {
    Permission: 'permission',
    Abort: 'abort',
    Switch: 'switch',
    SetSessionConfig: 'set-session-config',
    KillSession: 'killSession',
    HandoffLocal: 'handoff-local',
    SpawnHappySession: 'spawn-happy-session',
    ForkSpawnSession: 'fork-spawn-session',
    StopSession: 'stop-session',
    StopRunner: 'stop-runner',
    ListMachineDirectory: 'list-directory',
    CreateMachineDirectory: 'create-directory',
    PathExists: 'path-exists',
    GitStatus: 'git-status',
    GitDiffNumstat: 'git-diff-numstat',
    GitDiffFile: 'git-diff-file',
    ReadFile: 'readFile',
    ReadGeneratedImage: 'readGeneratedImage',
    ReadGeneratedFile: 'readGeneratedFile',
    WriteFile: 'writeFile',
    ListDirectory: 'listDirectory',
    GetDirectoryTree: 'getDirectoryTree',
    UploadFile: 'uploadFile',
    DeleteUpload: 'deleteUpload',
    Ripgrep: 'ripgrep',
    Difftastic: 'difftastic',
    Bash: 'bash',
    ListSlashCommands: 'listSlashCommands',
    ListSkills: 'listSkills',
    ListCodexModels: 'listCodexModels',
    ListCursorModels: 'listCursorModels',
    ListPiModels: 'listPiModels',
    ListOpencodeModels: 'listOpencodeModels',
    ListOpencodeModelsForCwd: 'listOpencodeModelsForCwd',
    ListOpencodeReasoningEffortOptions: 'listOpencodeReasoningEffortOptions',
    ListCcSwitchProviders: 'listCcSwitchProviders',
    ValidateCcSwitchProvider: 'validateCcSwitchProvider',
    ListImportableSessions: 'listImportableSessions',
    ResolveImportableSession: 'resolveImportableSession'
} as const

export type RpcMethod = typeof RPC_METHODS[keyof typeof RPC_METHODS]
